version: v1.0.0

dsn: memory

serve:
  public:
    base_url: http://127.0.0.1:4433/
    port: 4433
  admin:
    base_url: http://identity-server:4434/
    port: 4434

selfservice:
  default_browser_return_url: /core/web-ui
  allowed_return_urls:
    - /*

  methods:
    password:
      enabled: true

  flows:
    error:
      ui_url: /core/web-ui/error

    logout:
      after:
        default_browser_return_url: /core/web-ui/login

    login:
      ui_url: /core/web-ui/login
      lifespan: 10m
      after:
        password:
          hooks:
            - hook: revoke_active_sessions
          default_browser_return_url: /core/web-ui

    # TODO remove -->
    registration:
      ui_url: /core/web-ui/register
      lifespan: 10m
      after:
        password:
          hooks:
            - hook: session
    # TODO <-- remove

log:
  level: debug
  format: text
  leak_sensitive_values: true

# TODO should be generated
secrets:
  cookie: # len=17
    - =qcoEW+yhi<@4k>i2
  cipher: # len=32
    - LN>c&wrz2&>}>7z^*m(<\[ae(F;-\tP}

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 8

identity:
  default_schema_id: person
  schemas:
    - id: person
      url: file:///etc/config/kratos/person_identity.schema.json
    - id: machine
      url: file:///etc/config/kratos/machine_identity.schema.json

courier:
  smtp:
    connection_uri: smtps://127.0.0.1:12346
