CREATE DATABASE IF NOT EXISTS `module_manager` COLLATE 'utf8mb4_general_ci';
CREATE DATABASE IF NOT EXISTS `secret_manager` COLLATE 'utf8mb4_general_ci';
CREATE DATABASE IF NOT EXISTS `kratos` COLLATE 'utf8mb4_general_ci';
GRANT ALTER, CREATE, CREATE VIEW, DELETE, DROP, INDEX, INSERT, REFERENCES, SELECT, SHOW VIEW, TRIGGER, UPDATE ON `module\_manager`.* TO 'core_user'@'%';
GRANT ALTER, CREATE, CREATE VIEW, DELETE, DROP, INDEX, INSERT, REFERENCES, SELECT, SHOW VIEW, TRIGGER, UPDATE ON `secret\_manager`.* TO 'core_user'@'%';
GRANT ALTER, CREATE, CREATE VIEW, DELETE, DROP, INDEX, INSERT, REFERENCES, SELECT, SHOW VIEW, TRIGGER, UPDATE ON `kratos`.* TO 'core_user'@'%';